@startuml

title "Assessment Framework"

agent "[[https://hl7.org/fhir/R4/questionnaire.html Questionnaire]]" as Q
agent  "[[https://hl7.org/fhir/R4/questionnaireresponse.html Questionnaire Response]]" as QR
agent  "[[StructureDefinition-SDOHCC-ObservationAssessment.html SDOHCC Observation Assessment]]" as OA
agent  "[[StructureDefinition-SDOHCC-ObservationScreeningResponse.html SDOHCC Observation Screening Response]]" as OSR
agent  "[[StructureDefinition-SDOHCC-Condition.html SDOHCC Condition]]" as C

Q -[hidden]r-> OA : hidden link to ensure OA is rendered after Q
QR -u-> Q : Canonical\nQuestionnaire
OSR -l-> QR : derivedFrom
OSR -u-> OSR : derivedFrom\nhasMember
C -d-> OSR : Evidence
C -l-> QR : Evidence
OSR -[hidden]u-> OA : hidden link to ensure OA is rendered after OSR
C -> OA : Evidence

@enduml
