@startuml
/'!theme bluegray'/
title Capacity Status Query Light Flow

participant "Referral Source" as A
participant "Referral Target" as B

autonumber
A -> B : Send email
A <- B : Post HealthcareService(s)
A --> A : Evaluate HealthcareService(s)\nCapacity Status - if no capacity\nrepeat Step 1 with\na different Referral Target or HealthcareService,\nelse proceed to Step 4
A --> A : Initiate Referral Light workflow
hide footbox

@enduml