@startuml
/'!theme bluegray'/
title Capacity Status Query Light Flow

participant "Role: Referral Source\nActor: Provider" as A
participant "Role: Referral Target\nActor: Community-Based Organization" as B

autonumber
A -> B : Get HealthcareService(s)
A -> A : Evaluate HealthcareService(s)\nCapacity Status - if no capacity\nrepeat Step 1 with\na different Referral Target or HealthcareService,\nelse proceed to Step 3
A -> A : Initiate (direct) / resume (indirect)\nreferral workflow
hide footbox
@enduml