@startuml
/'!theme bluegray'/
title Detailed Direct Workflow

participant "Referral Source" as A
participant "Referral Target (CBO)" as B

A --> A : Create ServiceRequest + Task
A -> B : Post Referral Task

B -> A : Get ServiceRequest + referenced resources
B --> B : Evaluate Referral\nUpdate Task Status (accepted)
B -> A : Subscription Notification (optional)
A -> A : Get Task
A -> A : Evaluate Task Status (accepted)
B --> B : Begin Work and update\nTask Status to In Progress
B --> A : Subscription Notification (optional)
A -> A : Evaluate Task Status (in-progress)
B --> B : Complete Service\nCreate Procedure(s) to\ndocument service(s) delivered\nUpdate Task Status to Completed
B --> A : Subscription Notification (optional)
A -> B : Get Task
A -> A : Evaluate Task Status (completed)
A -> B : Get Procedure(s)
A -> A : Update ServiceRequest to Completed\nUpdate Goal as appropriate

@enduml