@startuml
/'!theme bluegray'/
title General Information Request Flow

participant "Requester" as A
participant "Patient" as B

autonumber
A -> A : Create [[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]] with question as .description
A -> B : Notify Patient
A <- B : Get [[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]]
A <- B : Update [[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]] (in-progress)
B -> B : Respond to Request for Information
A <- B : Update [[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]] (completed)\nTask.output includes text of response
hide footbox


@enduml