@startuml

title "Goal Management Framework"

agent "Goal" as G
agent  "Observation Screening or Assessment" as OSR
agent  "Condition" as C

C -[hidden]u-> OSR : hidden link to ensure OSR is rendered after C
G -r-> OSR : Addresses /\nOutcomeReference
G -r-> C : Addresses

@enduml