@startuml
/'!theme bluegray'/
title Review Material Request Flow

participant "Requester" as A
participant "Patient" as B

autonumber
A -> A : Create [[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]] and reference contacts as .input
A -> B : Notify Patient
A <- B : Get [[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]]
A <- B : Get Contact(s) via [[StructureDefinition-SDOHCC-HealthcareService.html SDOHCC Healthcare Service]]
A <- B : Update [[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]] (in-progress)
B -> B : Select Contact(s) to share
A <- B : Update [[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]] (completed)\nTask.output includes chosen contact
hide footbox

@enduml