@startuml

title "Patient Engagement Framework"

agent "[[StructureDefinition-SDOHCC-TaskForPatient.html SDOHCC Task for Patient]]" as T
agent  "[[https://hl7.org/fhir/R4/questionnaire.html Questionnaire]]" as Q
agent  "[[StructureDefinition-SDOHCC-HealthcareService.html SDOHCC Healthcare Service]]" as H
agent  "[[https://hl7.org/fhir/R4/documentreference.html Document Reference]]" as D
agent  "[[https://hl7.org/fhir/R4/questionnaireresponse.html Questionnaire Response]]" as QR


T -u-> Q : input
T -u-> H : input
T -l-> D : input
T -l-> D : output
T -u-> QR : output
T -> T : partOf

@enduml