@startuml

title "Referral Management Framework"

agent "[[StructureDefinition-SDOHCC-Goal.html SDOHCC Goal]]" as G
agent  "[[StructureDefinition-SDOHCC-TaskForReferralManagement.html SDOHCC Task for Referral Management]]" as T
agent  "[[StructureDefinition-SDOHCC-ObservationAssessment.html SDOHCC Observation Assessment]]\nor [[StructureDefinition-SDOHCC-ObservationScreeningResponse.html SDOHCC Observation Screening Response]]" as OSR
agent  "[[StructureDefinition-SDOHCC-ServiceRequest.html SDOHCC ServiceRequest]]" as SR
agent  "[[StructureDefinition-SDOHCC-Procedure.html SDOHCC Procedure]]" as P
agent  "[[StructureDefinition-SDOHCC-Condition.html SDOHCC Condition]]" as Cond
agent  "[[StructureDefinition-SDOHCC-Consent.html SDOHCC Consent]]" as Cons

SR -l-> G : pertainsToGoal
SR -r-> Cons : supportingInfo
SR -d-> OSR : Reason
SR -d-> Cond : Reason
P -u-> SR : basedOn
P -u-> Cond : Reason
P -u-> OSR : Reason
T -> SR : Focus
T -> P : Output
T -> T : partOf
T -[hidden]r-> Cons : hidden link to ensure G is rendered after T

@enduml