@startuml
/'!theme bluegray'/
title Capacity Status Indirect Flow

participant "Referral Source" as RS
participant "Intermediary (CP)" as CP
participant "Referral Target (CBO)" as CBO

== Create Service Request ==
RS --> RS : Create ServiceRequest + Task
RS -> CP : Post Referral Task

== Initial Processing ==
CP -> RS : Get ServiceRequest + referenced resources
CP --> CP : Evaluate Referral\n(Update Task Status)\nIdentify candidate Referral Target(s)
CP --> RS : Subscription Notification (optional)


== Capacity Checking ==
opt #yellow 
    RS -> CP : Get Task
    CP -> CBO : Get HealthcareService(s)
    RS --> RS : Evaluate Task Status (accepted)
    CP -> CP : Evaluate HealthcareService\nCapacity Status\nUpdate Task Status
end

== Referral Creation ==
CP -> CBO : Create ServiceRequest\n(based on Referral)
CP -> CBO : POST CP Task to CBO

CBO -> CP : Get ServiceRequest + resources
CP --> CBO : ServiceRequest + Task
CBO -> CBO : Evaluate Referral\nUpdate Task Status

== In Progress ==
CBO -> CP : Subscription Notification (optional)
CP -> CP : Evaluate Task Status\nUpdate to In Progress
    CP -> RS : Subscription Notification (optional)
    RS -> RS : Evaluate Status (in-progress)

== Completion ==
CBO -> CBO : Complete Service\nCreate Procedure(s)\nUpdate Task Status to Completed
CBO -> CP : Get Procedure(s)

CP -> CP : Link Procedure(s)\nUpdate Task Status to Completed
CP -> RS : Subscription Notification (optional)

RS -> RS : Evaluate Status (completed)
RS -> RS : Get Procedure(s)

== Final Update ==
RS -> RS : Update ServiceRequest to Completed\nUpdate Goal as appropriate

@enduml